[GeneralConfig]
    APIUrl = "http://localhost:7950"
    ElasticDatabaseAddress = "http://localhost:9200"
    Username         = ""
    Password         = ""
    DelegationLegacyContractAddress = "erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt"
    StakingContractAddress = "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l"


[AddressPubkeyConverter]
    #Length specifies the length in bytes of an address
    Length = 32
    # Type specifies the type of public keys: hex or bech32
    Type = "bech32"